
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Fri May 15 18:30:10 GMT-03:00 2026
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 8;
  public static final int MENOS = 5;
  public static final int PTVIRG = 2;
  public static final int IDENT = 20;
  public static final int ABRE_PARENT = 10;
  public static final int FECHA_PARENT = 11;
  public static final int KW_IF = 16;
  public static final int PTO = 3;
  public static final int OP_RELACIONAL = 18;
  public static final int ABRE_COLCH = 14;
  public static final int FECHA_COLCH = 15;
  public static final int MAIS = 4;
  public static final int NUMBER = 19;
  public static final int EOF = 0;
  public static final int MULT = 7;
  public static final int DIV = 6;
  public static final int error = 1;
  public static final int ASSIGN = 9;
  public static final int ABRE_CHAVE = 12;
  public static final int FECHA_CHAVE = 13;
  public static final int KW_ELSE = 17;
}

